### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by splaisan** [lh3/bioawk#23]
```
make
yacc -d awkgram.y
make: yacc: Command not found
Makefile:50: recipe for target 'ytab.o' failed
make: *** [ytab.o] Error 127
```
no ytab.o file while Makefile is including one

solved after installing bison (not present under ubuntu by default

Maybe nice to add to the readme.

Thanks for the great tool

**Comment by lh3** [comment]
added via 9bbde84.

**Comment by splaisan** [comment]
that was quick :-)
THX
