### ISSUE TITLE
recipe for target 'ytab.o' failed

### ISSUE THREAD

**Issue by PycnopodiaD** [lh3/bioawk#28]
Hi 
I want to install biohawk on the latest ubuntu (18.04) but I am getting this error after running make;

~/bioawk$ make
yacc -d awkgram.y
make: yacc: Command not found
Makefile:50: recipe for target 'ytab.o' failed
make: *** [ytab.o] Error 127

Any thoughts? (sorry if it is an easy fix)
Thanks

**Comment by lh3** [comment]
You need to have bison or byacc installed.

**Comment by PycnopodiaD** [comment]
works with bison, thanks.
