### ISSUE TITLE
compilation fatal error - missing zlib.h

### ISSUE THREAD

**Issue by janxkoci** [lh3/bioawk#39]
Hi,

I tried to compile bioawk after cloning it from this repo and installing `byacc` (using `sudo apt install byacc` on elementary OS Hera / Ubuntu 18.04), but I got fatal error:
```
jena@cloudbook:~/bin/bioawk$ make
yacc -d awkgram.y
yacc: 43 shift/reduce conflicts, 85 reduce/reduce conflicts.
mv y.tab.c ytab.c
mv y.tab.h ytab.h
gcc -g -Wall -O2 -c ytab.c
gcc -g -Wall -O2   -c -o b.o b.c
gcc -g -Wall -O2   -c -o main.o main.c
gcc -g -Wall -O2   -c -o parse.o parse.c
gcc -g -Wall -O2 maketab.c -o maketab
./maketab >proctab.c
gcc -g -Wall -O2   -c -o proctab.o proctab.c
gcc -g -Wall -O2   -c -o tran.o tran.c
gcc -g -Wall -O2   -c -o lib.o lib.c
gcc -g -Wall -O2   -c -o run.o run.c
gcc -g -Wall -O2   -c -o lex.o lex.c
gcc -g -Wall -O2   -c -o addon.o addon.c
addon.c:241:10: fatal error: zlib.h: Adresář nebo soubor neexistuje
 #include <zlib.h> /* FIXME: it would be better to drop this dependency... */
          ^~~~~~~~
compilation terminated.
make: *** [<vestavěný>: addon.o] Chyba 1
```

Any help would be welcome.

**Comment by NRX-044** [comment]
https://stackoverflow.com/questions/36374267/how-to-fix-fatal-error-zlib-h-no-such-file-or-directory

**Comment by janxkoci** [comment]
Huh, I don't even have that machine anymore :grinning: 

I tried now on my new laptop, where I had the `zlib1g-dev` package already present (same system as above, maybe I pulled it with something else) and compilation went through without issue. I only installed `bison` parser generator beforehand. I will close this, thanks.
