### ISSUE TITLE
bioawk

### ISSUE THREAD

**Issue by Fady63** [lh3/bioawk#40]
how to solve this problem when trying to run make in bioawk file?
yacc -d awkgram.y
awkgram.y: warning: 43 shift/reduce conflicts [-Wconflicts-sr]
awkgram.y: warning: 85 reduce/reduce conflicts [-Wconflicts-rr]
mv y.tab.c ytab.c
mv y.tab.h ytab.h
gcc -g -Wall -O2 -c ytab.c
make: gcc: Command not found
Makefile:50: recipe for target 'ytab.o' failed
make: *** [ytab.o] Error 127

**Comment by janxkoci** [comment]
In 2025, I'd do just

```bash
mamba install bioconda::bioawk
```

Assuming unix-like system - Linux, macOS, WSL.
